export const LOAD_TRACK_DATA_SUCCESS = 'LOAD_TRACK_DATA_SUCCESS';
export const LOAD_TRACK_DATA_FAILURE = 'LOAD_TRACK_DATA_FAILURE';

export const LOAD_ARTIST_DATA_SUCCESS = 'LOAD_ARTIST_DATA_SUCCESS';
export const LOAD_ARTIST_DATA_FAIL = 'LOAD_ARTIST_DATA_FAIL';

export const LOAD_TOP_TRACKS_DATA_SUCCESS = 'LOAD_TOP_TRACKS_DATA_SUCCESS';
export const LOAD_TOP_TRACKS_DATA_FAILURE = 'LOAD_TOP_TRACKS_DATA_FAILURE';

export const LOAD_TOP_ARTISTS_DATA_SUCCESS = 'LOAD_TOP_ARTISTS_DATA_SUCCESS';
export const LOAD_TOP_ARTISTS_DATA_FAILURE = 'LOAD_TOP_ARTISTS_DATA_FAILURE';

export const LOAD_USER_PLAYLIST_DATA_SUCCESS =
  'LOAD_USER_PLAYLIST_DATA_SUCCESS';
export const LOAD_USER_PLAYLIST_DATA_FAILURE =
  'LOAD_USER_PLAYLIST_DATA_FAILURE';

export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

export const LOAD_RECENT_TRACKS_DATA_SUCCESS =
  'LOAD_RECENT_TRACKS_DATA_SUCCESS';
export const LOAD_RECENT_TRACKS_DATA_FAILURE =
  'LOAD_RECENT_TRACKS_DATA_FAILURE';

export const SET_FAVOURITE_TRACK = 'SET_FAVOURITE_TRACK';

export const TOGGLE_ACTION_MENU = 'TOGGLE_ACTION_MENU';
