// Track Action Types
export const LOAD_TRACK_DATA_SUCCESS = 'LOAD_TRACK_DATA_SUCCESS';
export const LOAD_TRACK_DATA_FAILURE = 'LOAD_TRACK_DATA_FAILURE';

// Top Track Action Types
export const LOAD_TOP_TRACKS_DATA_SUCCESS = 'LOAD_TOP_TRACKS_DATA_SUCCESS';
export const LOAD_TOP_TRACKS_DATA_FAILURE = 'LOAD_TOP_TRACKS_DATA_FAILURE';

// Top Artists Action Types
export const LOAD_TOP_ARTISTS_DATA_SUCCESS = 'LOAD_TOP_ARTISTS_DATA_SUCCESS';
export const LOAD_TOP_ARTISTS_DATA_FAILURE = 'LOAD_TOP_ARTISTS_DATA_FAILURE';

// Drawer Action Types
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';

// Recent Track Action Types
export const LOAD_RECENT_TRACKS_DATA_SUCCESS =
  'LOAD_RECENT_TRACKS_DATA_SUCCESS';
export const LOAD_RECENT_TRACKS_DATA_FAILURE =
  'LOAD_RECENT_TRACKS_DATA_FAILURE';
